name: geocompy
channels:
  - conda-forge
  - default
dependencies:
  - python>=3.9
  - bokeh
  - cartopy==0.19.0
  - cython
  - folium
  - geopandas
  - geopy
  - geoviews
  - hvplot
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - proj
  - rasterio
  - shapely<1.8
  - topojson
